platform :ios, '9.3'
use_frameworks!

target 'Binge' do

  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'MBProgressHUD', '~> 0.9.2'
  pod 'TMDBCore', :path => '../TMDBCore'
  pod 'BingeUI', :path => '../BingeUI'

end